### PR TITLE
Add success/failure methods to make the UI better

### PR DESCRIPTION
**Pull request by robkinyon**
These make it nicer to work with the command object.

### CODE REVIEW

**Comment by book** [comment]
I'm not really fond of hiding a blocking loop (which, in addition, is "busy waiting") behind relatively innocuous names like `success` and `failure`. Also, this is basically running the command and waiting for the exit status, which could as easily be done with `qx` or `system`.

However, when wanting to use `System::Command` for something that was not as well-behaved as git ([Git::Repository](https://metacpan.org/pod/Git::Repository) is the main user of the module) , I found myself thinking about using a `select()` loop to process the output/errput, no matter which order it came out in.

Right now, I'm thinking about adding a `loop_for` method, that would work like so:

    # blocks until the command is completed
    $cmd->loop_for(
        stdout => sub { ... }, # callbacks run whenever there's data available
        stderr => sub { ... }, # on any of the read handles
    );

There should be some facilities to break out of the loop early, and maybe hooks for more callbacks (at beginning and end, at least).

Obviously, missing callbacks would mean that the data coming out of the filehandles is sent to `/dev/null`, so if `loop_for` returned `$self->exit` or `$self->exit == 0`, it would be really easy to mimic your proposed `success` and `failure` methods, with some nice callback support in case one does actually want to do something with the output/errput.

**Comment by robkinyon** [comment]
While I understand the desire to (and well-written implementation of!) have background-ed long-running processes that can be checked at useful intervals to me, I suspect the more common use-case of `System::Command` will be to replace Bash scripts with a sane `system` replacement. (That's been my use-case.) This use-case is best served by having something which polls for completion before continuing.

Adding a `loop_for` makes a lot of sense and continues with the idea of having parallelization built into the core architecture. But, adding `success`/`failure` right now doing the `select()` polling for completion wouldn't interfere with that. Once `loop_for` exists, `success()` would be rewritten to take advantage of that.

The other thing that could work is to add a `wait_for_completion` method which wraps the polling. Then, people can choose to use that method. I still think, though, `success` and `failure` need to drain the command states.

**Comment by book** [comment]
0bfd8399413149c6b82822ddfe7949f433286b2e contains a first implementation of `loop_on`.

I'm quite happy that it worked as expected the first time... ;-)

**Comment by book** [comment]
It's not perfect, in the sense that it does not preserve the order in which the lines were sent, but I suspect it's hard to fix at this level (e.g. buffering).

This example will show what I mean:

    perl -Ilib -MSystem::Command -MTerm::ANSIColor -e '
        System::Command->loop_on(
            command => [
                qw( perl -le ), q{ print { $i++ % 10 ? STDOUT : STDERR } $i for 1..30 }
            ],
            stdout => sub { print shift },
            stderr => sub { print shift, " *" },
        );
    ' | head                                                                      
    1
    2
    1 *
    3
    11 *
    4
    21 *
    5
    6
    7
    8

**Comment by robkinyon** [comment]
The buffering you're speaking of is a standard problem when dealing with STDOUT and STDERR. I'm curious why it printed 1 to bother STDOUT and STDERR - that shouldn't have happened.

That said, do you intend to implement failure/success on top of loop_on()? Those are the things I care about. :)

**Comment by book** [comment]
> The buffering you're speaking of is a standard problem when dealing with STDOUT and STDERR. I'm curious why it printed 1 to bother STDOUT and STDERR - that shouldn't have happened.

This is an excellent remark. Running the one-liner on the command-line shows the `1`, `11`, `21` lines only once. And piping either standard output or standard error to `/dev/null` shows the expected result.

I fact, it seems I did something wrong when copy/pasting, because running the following again show the expected output:

    perl -Ilib -MSystem::Command -MTerm::ANSIColor -e '
        System::Command->loop_on(
            command => [
                qw( perl -le ), q{ print { $i++ % 10 ? STDOUT : STDERR } $i for 1..30 }
            ],
            stdout => sub { print shift },
            stderr => sub { print "* ", shift },
        );
    ' | head
    2
    * 1
    3
    * 11
    4
    * 21
    5
    6
    7
    8

This time I've put the `*` at the beginning of the line, because the line contains an embedded newline.

**Comment by book** [comment]
> That said, do you intend to implement failure/success on top of loop_on()? Those are the things I care about. :)

I'm still wary of adding too many utility methods. For now `loop_on` returns `$self->exit == 0` (i.e. true for success and false for failure), which should make `failure`/`success` really easy to add if needed.

Also, your current implementation of `success`/`failure` will hang as soon as the pipes are filled with data, because you're not draining them. A simple `perl -E 'say $i++ for 1..1e6'` command will expose the issue.

**Comment by robkinyon** [comment]
It sounds like you should decline this PR (which is fine) and I'll submit a
new one built on top of loop_on().

On Tue, Jan 12, 2016 at 11:10 AM, Philippe Bruhat (BooK) <
notifications@github.com> wrote:

> That said, do you intend to implement failure/success on top of loop_on()?
> Those are the things I care about. :)
>
> I'm still wary of adding too many utility methods. For now loop_on
> returns $self->exit == 0 (i.e. true for success and false for failure),
> which should make failure/success really easy to add if needed.
>
> Also, your current implementation of success/failure will hang as soon as
> the pipes are filled with data, because you're not draining them. A simple perl
> -E 'say $i++ for 1..1e6' command will expose the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/book/System-Command/pull/20#issuecomment-170959996>.
>



-- 
Thanks,
Rob Kinyon
http://greenfishbluefish.com/

**Pull request closed without merging**
